services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile

  mongo:
    image: mongo
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data/:/data/db

  redis:
    image: redis
    ports:
      - 6379
    tty: true
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data/:/data

  server:
    image: todo-backend
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://todo-app-redis-1:6379
      - MONGO_URL=mongodb://the_username:the_password@todo-app-mongo-1/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
